services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: amadeus
      POSTGRES_USER: amadeus
      POSTGRES_PASSWORD: amadeus
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U amadeus"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://amadeus:amadeus@db:5432/amadeus
      REDIS_URL: redis://redis:6379/0
      AMAD_USE_MOCK: ${AMAD_USE_MOCK:-true}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - ./vendor:/app/vendor
    ports:
      - "8000:8000"

  frontend:
    build:
      context: frontend/amadeus-ui
      dockerfile: ../docker/frontend.Dockerfile
    depends_on:
      api:
        condition: service_started
    environment:
      API_URL: http://api:8000
    volumes:
      - ./frontend/amadeus-ui:/app/frontend/amadeus-ui
      - frontend_node_modules:/app/frontend/amadeus-ui/node_modules
    ports:
      - "4200:4200"
    command: npm run start -- --host 0.0.0.0 --port 4200

volumes:
  db_data:
  frontend_node_modules:
